FROM ubuntu:25.04

FROM ubuntu:25.04

RUN apt-get update && \
    apt-get install -y make build-essential ca-certificates iputils-ping && \
    update-ca-certificates && \
    rm -rf /var/lib/apt/lists/*